export { default as PurpleBackground } from './PurpleBackground'
export { default as SectionWrapper } from './SectionWrapper'
export { default as DeleteContent } from './DeleteContent'
export { default as WhiteWrapper } from './WhiteWrapper'
export { default as ImageUpload } from './ImageUpload'
export { default as AvatarModal } from './AvatarModal'
export { default as ErrorAlert } from './ErrorAlert'
export { default as ColorInput } from './ColorInput'
export { default as InputField } from './InputField'
export { default as DirectBtn } from './DirectBtn'
export { default as Modal } from './Modal'
export * from './svgs/types.d'
export * from './types.d'
export * from './svgs'
