export { default as PurpleBackground } from './PurpleBackground'
export { default as WhiteWrapper } from './WhiteWrapper'
export { default as SectionWrapper } from './SectionWrapper'
export { default as GoBackBtn } from './GoBackBtn'
export { default as Modal } from './Modal'
export { default as InputField } from './InputField'
